"""empty message

Revision ID: 8674bb0ece12
Revises: be0a73ed2e88
Create Date: 2021-02-25 20:56:39.209992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8674bb0ece12'
down_revision = 'be0a73ed2e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.String(length=140), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    # ### end Alembic commands ###
